### ISSUE TITLE
How do I obtain an orgToken?

### ISSUE THREAD

**Issue by jwhits** [deanlyoung/homebridge-awair#1]
I tried to get access to the Awair developer dashboard but I didn't get approved. Is there another way to get the orgToken or to get this working with Homebridge?

**Comment by deanlyoung** [comment]
@jwhits is this for a personal project, an office, or a company?

**Comment by jwhits** [comment]
Personally project.

**Comment by deanlyoung** [comment]
What kinds of things would you like to use the API for with HomeBridge? (If you don’t mind my asking)

**Comment by jwhits** [comment]
The first one I want to set up, is in my bedroom have the exhaust fan turn on via a smart outlet when the CO2 gets high and then have it turn off when the CO2 drops. I notice a clear difference to how I feel when the CO2 is high. At the moment I’m using IFTTT however it’s a bit clunky and unreliable as there is only an IFFT trigger for high CO2 so I then have to have Stringify tuner to turn the exhaust fan off. Sometimes it works sometimes it doesn’t.

**Comment by deanlyoung** [comment]
Got it! Makes sense. This is mostly an Enterprise API at the moment (and I believe the have endpoints in this integration may be deprecated), but keep an eye on this space if anything changes!

**Comment by jwhits** [comment]
Thanks for letting me know, I’d love to see the API opened up :) or at the very least a low CO2 trigger for IFTTT.

**Comment by quicklywilliam** [comment]
It sounds like Awair is finally opening up their API to folks!

https://twitter.com/getawair/status/1027688925958041601

**Comment by deanlyoung** [comment]
@jwhits @quicklywilliam yep! You should be approved now. Let me know if you have any questions.

Also, if you have any feedback or can make a pull request to get this plugin to work, I could really use the help on the last mile 🤔

**Comment by jwhits** [comment]
I just got approved for the API :) so will play around soon
