### ISSUE TITLE
Add option to hide unwanted sensors in home app

### ISSUE THREAD

**Issue by ghost** [deanlyoung/homebridge-awair#10]
Would be nice. Awesome plugin!

**Comment by deanlyoung** [comment]
@malmentm the current "main" sensor is the Air Quality service. In your case, would you always want that one available, or were you thinking of another as the "main" service? If I can leave that as the main service, then it becomes a bit easier, however if another becomes the main service, then it gets a bit more complicated...

**Comment by ghost** [comment]
I was thinking of the possibility to hide for example the temperature sensor if you already got another one in the same room

**Comment by deanlyoung** [comment]
@malmentm got it! I'm wondering if this will still be relevant with the changes to the way HomeKit displays devices in iOS 13. And you can always "hide" a sensor from the "status" section (at the top of the homescreen) in the settings of the device.

**Comment by ghost** [comment]
Yes. You’re right. This is not necessary with iOS 13 :)
