### ISSUE TITLE
Awair Glow C 

### ISSUE THREAD

**Issue by lfiocco** [deanlyoung/homebridge-awair#11]
How many devices and what type does this add to home app?

Can you control the outlet?

Can you control the light?

**Comment by deanlyoung** [comment]
Glow C will appear as 3 tiles on iOS <13 and 1 tile (grouped) on iOS ≥13.

Outlet isn't supported yet via the APIs, ~but is coming soon~. Light control isn't supported yet in this plugin, but ~will~ may be coming eventually.
