### ISSUE TITLE
Not seeing VOC or Dust readings in Home app

### ISSUE THREAD

**Issue by mikef147** [deanlyoung/homebridge-awair#12]
Just have 4, quality, CO alarm (triggered/untriggered), humidity level and temp.  How can I get VOC and dust levels in Home?

**Comment by deanlyoung** [comment]
There is a way to view the data, but it's hidden...
https://imgur.com/gallery/B1EmrPD

**Comment by DMBlakeley** [comment]
First, @deanlyoung - thanks for your work on this plug-In!

Just to add to this a bit. I learned quite a bit studying this plug-in about HomeKit and the hierarchy of Accessory/Services/Characteristics for HomeKit devices. Homebridge can only implement capabilities which are available in HomeKit. Homebridge-awair provides a mapping between the Awair-API -> homebridge and hombridge -> HomeKit.

In the case of Awair, the device is a HomeKit Accessory which has the following services and (Characteristics):

- Air Quality Sensor (**Air Quality**, PM2.5, PM10, VOC Density)
- Temperature Sensor (**Current Temperature**)
- Humidity Sensor (**Current Relative Humidity**)
- Carbon Dioxide Sensor (**Normal/Abnormal**, Carbon Dioxide Level, Peak Carbon Dioxide Level)

The **bolded** characteristics is information which is displayed on the tile in HomeKit. Also note that there is not a "dust" characteristic in HomeKit. The Awair plugin displays dust through the PM10 characteristic.

Going back to the original question. HomeKit does not have an Accessory/Characteristic combination that can display VOC and dust levels on the tile. VOC and dust are characteristics of the Air Quality Sensor which display Air Quality (Excellent, Good Fair, Inferior or Poor) via the tile. Other characteristics are only available via the Settings workaround noted above.

A nice tool to understand the HomeKit hierarchy is the "HomeKit Accessory Simulator" which can be downloaded from the Apple Developers webpage.
