### ISSUE TITLE
Force C or F temperature?

### ISSUE THREAD

**Issue by mmorper** [deanlyoung/homebridge-awair#13]
I have four Awair devices, however one of the four is returning Celsius into Homebridge even though it is configured in the iOS app to return Fahrenheit. Is it possible to explicitly request Fahrenheit via the API to return back into Homebridge? If not, any ideas as to what may be causing this? Thanks in advance.

**Comment by DMBlakeley** [comment]
I have been studying this plugin as a way to understand HomeKit sensor implementation via Homebridge a bit better. Also interesting to see how the Awair API maps to Homebridge.

I looked into your PR and although possible to have an entry in the config to select C or F, I found that HomeKit handles temperature format depending on your iOS device preferences (Settings/General/Language & Region). Per the Awair API docs, temperatures are in Centigrade and only converted to Fahrenheit based on your device settings.

To debug a bit you may want to add `"logging": true` to each of you Awair accessory entries in the `config.json` file (don't forget the `","` on the line before. This will confirm that each of your 4 devices is reporting back data from the Awair servers. I have also noted that the Awair Hobbyist tier has limits on the number of requests per 24 hours. Not sure if you are hitting this limit with 4 devices.

Having said that I would make sure that your iOS devices are updated to the latest (13.4.1), your HomeKit bridge (HomePod, Apple TV, etc.) are also updated. Then reboot your iOS devices, your bridge,  as well as Homebridge and check if you still have the problem.

**Comment by deanlyoung** [comment]
I agree with @DMBlakeley. I personally rely on iOSes settings, and while technically possible to return ºF from the Awair Developer APIs /air-data/ endpoints, I think this is better (more properly?) handled by the HomeKit UI. If there is a strong preference or reason to reconsider, please re-open, but I am going to close this and mark as "Won't Fix" for now.

By the way, the user interface in the Awair app and device display has no bearing on the Developer API units. That is implemented via a query parameter on the /air-data/ endpoint.
