### ISSUE TITLE
User does not have permission to call RAW endpoint

### ISSUE THREAD

**Issue by jwhits** [deanlyoung/homebridge-awair#3]
Great job reworking the plugin.

I have it running but I don't seem to have permission to call the Awair API endpoint?

This is the URL it's trying to request
`http://developer-apis.awair.is/v1/users/self/devices/awair/9339/air-data/latest `
This is what I see in the log
`[2018-9-3 20:28:54] [Awair Bedroom] Error contacting Awair API: StatusCodeError: 401 - {"message":"User 7596 does not have permission to call RAW endpoint"}`

I had no issues getting my devID and DevType. I also tried requesting the above url with my Authorization Bearer directly in terminal and got the same 401 error above.

**Comment by deanlyoung** [comment]
@jwhits oh, sorry! Ideally, this was the reason for setting up awairnode as a nodeJS wrapper for Awair API calls to make switching between URL endpoints easier. /latest will be added to the free tier soon. For now, I can change it to default to /15-min-avg so that it works.

**Comment by deanlyoung** [comment]
@jwhits give it a try now. Should be homebridge-awair@2.5.2

**Comment by jwhits** [comment]
It is now working :)
