### ISSUE TITLE
Help me ..

### ISSUE THREAD

**Issue by wonderfullay** [deanlyoung/homebridge-awair#8]
curl -X GET \
http://developer-apis.awair.is/v1/users/self/devices \
-H 'Authorization: Bearer {developer-token}'

If you put the above command (Token is received), it will appear as below. What should I do?

"The resource requires authentication, which was not supplied with the request"

**Comment by deanlyoung** [comment]
@wonderfullay and you've replaced {developer-token} with your token from the Awair Developer Console?

**Comment by wonderfullay** [comment]
yes.

**Comment by deanlyoung** [comment]
Can you send me a personal message on github or email us at developer@getawair.com?

**Comment by lordbeniel** [comment]
how was this originally resolved? I'm having the same issue

**Comment by lordbeniel** [comment]
nevermind- through my own idiocy I'd put the bearer in twice
